### MY DETAILS

Name: Arsalan Ahmed

Roll Number: 21I-0271

### IMPORTANT LIBRARIES

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

Q1

In [21]:
#PRINT ALL THE OUTPUTS 
P_Box1=0.5
P_Box2=0.5
Box1=["R","R","W","W","W","W","W"]
Box2=["R","R","R","W","W","W","W","W"]
TotalRed=5
TotalWhite=10
TotalBalls=len(Box1)+len(Box2)
print("Total Balls: ",TotalBalls)

# P(Reds)
P_Reds= TotalRed/TotalBalls
print("P(Reds): ",P_Reds)

# P(Box1)
print("P(Box1): ",P_Box1)

# P(Box1|Red)
Red_Box1=0
for x in Box1:
    if x=="R":
        Red_Box1+=1
P_Box1Red= Red_Box1/TotalRed
print("P(Box1|Red)",P_Box1Red)

# P(RED|Box1)
P_RedBox1=(P_Box1Red*P_Reds)/P_Box1
print("P(Red|Box1)",P_RedBox1)

Total Balls:  15
P(Reds):  0.3333333333333333
P(Box1):  0.5
P(Box1|Red) 0.4
P(Red|Box1) 0.26666666666666666


Q2

In [96]:
#APPLY NECESSARY ML CONCEPTS THAT MAY BE USEFUL
x=torch.tensor([1,2,3,4,5,6],dtype=torch.float32).view(-1,1)
y=x+2 #THE LINEAR RELATIONSHIP
print(x)
print(y)
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)
        self.linear2=nn.Linear(1,1)
        self.act_fn=nn.ReLU()
    def forward(self,x):
        output1=self.linear(x)
        out=self.act_fn(output1)
        output2=self.linear(out)
        return output2
model=LinearModel()
criterion=nn.MSELoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)
epochs=100
for i in range (epochs):
    output=model(x)
    loss=criterion(output,y)
    print(f"After {i} epochs the loss is {loss}")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
model.eval()
test=torch.tensor([200],dtype=torch.float32)
pred=model(test)
print(f"At tensor {test}, the predicted value is, {pred}")

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
tensor([[3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
After 0 epochs the loss is 14.558199882507324
After 1 epochs the loss is 2.1123909950256348
After 2 epochs the loss is 0.2975841462612152
After 3 epochs the loss is 0.18503053486347198
After 4 epochs the loss is 0.09406150132417679
After 5 epochs the loss is 0.06855446845293045
After 6 epochs the loss is 0.053668733686208725
After 7 epochs the loss is 0.04762806370854378
After 8 epochs the loss is 0.04414160177111626
After 9 epochs the loss is 0.042101819068193436
After 10 epochs the loss is 0.0406019389629364
After 11 epochs the loss is 0.03937486186623573
After 12 epochs the loss is 0.03827284649014473
After 13 epochs the loss is 0.03724181652069092
After 14 epochs the loss is 0.03625579923391342
After 15 epochs the loss is 0.035303905606269836
After 16 epochs the loss is 0.03438114747405052
After 17 epochs the loss 

Q3

In [99]:
#LOOP HERE
model=LinearModel()
criterion=nn.MSELoss()
pro=[]
for p in model.parameters():
    print(p)
    print(p.pow(2.0).sum())
    pro.append(p.pow(2.0).sum())
optimizer=optim.SGD(pro,lr=0.01)
epochs=100
for p in model.parameters():
    p=p.pow(2.0).sum()
    for i in range (epochs):
        output=model(x)
        loss=criterion(output,y)
        print(f"After {i} epochs the loss is {loss}")
        print("Optimization",p)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

Parameter containing:
tensor([[-0.9715]], requires_grad=True)
tensor(0.9437, grad_fn=<SumBackward0>)
Parameter containing:
tensor([0.8610], requires_grad=True)
tensor(0.7413, grad_fn=<SumBackward0>)
Parameter containing:
tensor([[0.4160]], requires_grad=True)
tensor(0.1731, grad_fn=<SumBackward0>)
Parameter containing:
tensor([0.4552], requires_grad=True)
tensor(0.2072, grad_fn=<SumBackward0>)
After 0 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 1 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 2 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 3 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 4 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 5 epochs the loss is 24.437353134155273
Optimization tensor(0.9437, grad_fn=<SumBackward0>)
After 6 epochs 

Q4

### WRITE HERE

Loss.backward()= This is used to calculate the loss and learn in backward propagation of the model.It also computes the gradient of current tensor wrt graph leaves.


optimizer.zero_grad()= This is a widely used gradient descent optimizing technique where gradient is set to zero to optimize the model. It resets the gradients of all optimized class tensors to zero or none.


optimizer.step()= Performs a single optimization step.


The following done in order will work in a way that loss.backward will compute the losses and the gradient of a current tensor, then optimizer.zero_grad will reset this gradient and the optimizer.step will move a single optimization step and move on to the next parameter, tensor and set of values. The problem with this is that the zero_grad after loss.backward will always reset the gradient therefore there will be no learning or change in loss.

In [82]:
### Thanks alot for teaching us sir, proud to be your student as I learned alot from you.